name: Auto Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          debug: true
          script: |
            cd /var/www/task_dashboard

            echo "Pull latest code"
            git pull origin main

            echo "Setup backend"
            cd backend
            python3 -m venv venv
            ./venv/bin/pip install -r requirements.txt

            echo "Build frontend"
            cd ../my-dashboard
            npm ci
            npm run build

            echo "Restart server"
            cd ..
            pm2 reload backend

            echo "Deploy complete"